# ==========================================
# APPLICATION
# ==========================================

spring.application.name=bank-queue-management-api

server.port=2026

logging.level.root=ERROR

logging.level.com.nsglobal.queue=INFO

# ==========================================
# DATASOURCE
# ==========================================
spring.datasource.url=jdbc:postgresql://localhost:5432/bank_queue_management_db
spring.datasource.username=sakazuki26
spring.datasource.password=2026@viking
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# JPA / HIBERNATE
# ==========================================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ==========================================
# FLYWAY
# ==========================================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# ==========================================
# LOGGING SQL
# ==========================================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# ==========================================
# ACTUATOR
# ==========================================
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

spring.profiles.active=dev


