# ==========================================
# APPLICATION
# ==========================================

spring.application.name=bank-queue-management-api

server.port=2026

logging.level.root=ERROR

logging.level.com.nsglobal.queue=INFO

# ==========================================
# DATASOURCE
# ==========================================
spring.datasource.url=jdbc:postgresql://localhost:5432/bank_queue_management_db
spring.datasource.username=sakazuki26
spring.datasource.password=2026@viking
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# JPA / HIBERNATE
# ==========================================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ==========================================
# FLYWAY
# ==========================================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# ==========================================
# LOGGING SQL
# ==========================================
logging.level.org.hibernate.SQL=INFO
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# ==========================================
# ACTUATOR
# ==========================================
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

#=============================================
# SCHEDULER TSK
spring.task.scheduling.pool.size=10
spring.task.execution.pool.core-size=10
spring.task.execution.pool.max-size=20
#=============================================

#============================
# SMS
#=============================
#notification.sms.enabled=false
#notification.sms.provider=mock
#=============================
# EMAIL
#==============================

#notification.email.enabled=false
#notification.email.provider=mock
#==========================================
# WhatsApp
#======================================
#notification.whatsapp.enabled=false
#==========================================
# Push
#============================================
##notification.push.enabled=false
#=============================================

com.nsglobal.queue.enterpriseName=NS GLOBAL BANK

com.nsglobal.queue.jwtSecret=Eblz+UfRhUON3l30ixeQfFiOs0x4lW6GzdqyvpzyCus=

com.nsglobal.queue.jwtExpiration=86400000


com.nsglobal.queue.counterCloseCron=0 0 18 * * MON-FRI

com.nsglobal.queue.counterOpenCron=0 0 8 * * MON-FRI

com.nsglobal.queue.dashboardRefreshCron=*/30 * * * * *

com.nsglobal.queue.absentTicketCron=0 * * * * *

com.nsglobal.queue.cleanupCron=0 0 2 * * *

com.nsglobal.queue.absentDelayMinutes=5

com.nsglobal.queue.historyRetentionDays=90

com.nsglobal.queue.cancelledTicketRetentionDays=30

spring.profiles.active=dev


